# Generated by Django 5.1.5 on 2025-02-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_keydetail_googleloginclientid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irapdetail',
            name='irap_treatment_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
