# Generated by Django 5.1.5 on 2025-02-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_irapdetail_irap_treatment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrecord',
            name='identity',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
