name: CI-CD-Driver

on:
  # Triggers the workflow on push or pull request events but only for the "staging" branch
  push:
    branches: [ "staging" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create folder if it doesn't exist
        run: |
          mkdir -p /home/ubuntu/driver
          
      - uses: actions/checkout@v4
        with:
          repository: driver-new-tech
          ref: staging
          path: /home/ubuntu/driver

      - name: Create .env file
        run: |
          "echo HOST_NAME=${{ secrets.HOST_NAME }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo HOST_URL=${{ secrets.HOST_URL }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo POSTGRES_USER: ${{ secrets.POSTGRES_USER }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo PGPASSWORD: ${{ secrets.PGPASSWORD }}" >> /home/ubuntu/driver/driver-new-tech/.env 
          "echo WINDSHAFT_FILES: ${{ secrets.WINDSHAFT_FILES }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo TIMEZONE: ${{ secrets.TIMEZONE }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo PROTOCOL: ${{ secrets.PROTOCOL }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo STATIC_ROOT: ${{ secrets.STATIC_ROOT }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo DIST_ROOT: ${{ secrets.DIST_ROOT }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo DRIVER_REDIS_PORT: ${{ secrets.DRIVER_REDIS_PORT }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}" >> /home/ubuntu/driver/driver-new-tech/.env
          "echo EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}" >> /home/ubuntu/driver/driver-new-tech/.env
