name: Deploy to EC2 and Push to ECR

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Aventior-Inc/driver-new-tech
          ref: staging

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create .env file for the Docker container
        run: |
          pwd
          ls -al
          echo "HOST_NAME=${{ secrets.HOST_NAME }}" > .env
          echo "HOST_URL=${{ secrets.HOST_URL }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> .env
          echo "WINDSHAFT_FILES=${{ secrets.WINDSHAFT_FILES }}" >> .env
          echo "TIMEZONE=${{ secrets.TIMEZONE }}" >> .env
          echo "PROTOCOL=${{ secrets.PROTOCOL }}" >> .env
          echo "CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}" >> .env
          echo "STATIC_ROOT=${{ secrets.STATIC_ROOT }}" >> .env
          echo "DIST_ROOT=${{ secrets.DIST_ROOT }}" >> .env
          echo "DRIVER_REDIS_PORT=${{ secrets.DRIVER_REDIS_PORT }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          ls -al
          # Give execute permission to production_host.sh
          chmod +x production_host.sh
          # Run the production_host.sh script
          ./production_host.sh
           # Build the Docker image
          docker-compose -f docker-compose.yml build
          docker image ls

      - name: Build Docker image and Push to ECR
        run: |
          # Log in to ECR
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
          
          # Tag the image for ECR
          docker tag driver-django:latest ${{ secrets.ECR_REPO }}:driver-django-${{ github.run_number }}
          docker tag driver-database:latest  ${{ secrets.ECR_REPO }}:driver-database-${{ github.run_number }}

          # Push the image to ECR
          docker push ${{ secrets.ECR_REPO }}:driver-django-${{ github.run_number }}
          docker push ${{ secrets.ECR_REPO }}:driver-database-${{ github.run_number }}

      - name: SSH into EC2 and Deploy with Docker Compose
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get public IP of GitHub Actions Runner
        id: get_ip
        run: |
          # Fetch the public IP address of the GitHub Actions runner using a public service
          IP_ADDRESS=$(curl -s https://ifconfig.me)
          echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV
          echo "GitHub Actions Runner IP: $IP_ADDRESS"

      - name: whitelisting ip on security group
        run: |
          SECURITY_GROUP_ID="${{ secrets.SECURITY_GROUP_ID }}"
          IP_ADDRESS="${{ env.IP_ADDRESS }}/32"
          aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr $IP_ADDRESS

      - name: Copy files from Ubuntu Runner to EC2
        run: |
          # Copy files from GitHub Actions runner to EC2 instance
          pwd
          ls -al
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} -r /home/runner/work/driver-new-tech/* ubuntu@${{ secrets.HOST_NAME }}:/home/ubuntu/
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Deploy on EC2 with Docker Compose
        run: |
          # SSH into EC2 and deploy using Docker Compose
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_NAME }} << EOF
            # Change to project directory and pull the latest image from ECR
            cd /opt
            
            # Ensure Docker Compose is available
            sudo apt-get install -y docker-compose

            # Pull the latest Docker image from ECR
            docker-compose pull

            # Start or restart the Docker containers using docker-compose
            docker-compose up -d

            # Clean up any stopped containers
            docker container prune -f
          EOF

      - name: Cleanup
        run: |
          # Clean up any sensitive data or files that were created
          rm -f private_key.pem
